"""Build the Module 7 learning-activity notebooks with nbformat.

Run:  python3 build_activities.py
Then: python3 -m nbconvert --execute --inplace --to notebook activity*.ipynb

The original briefs point at hosted demos that are now dead or Colab-only
(titanicexplainer.herokuapp.com, aix360.mybluemix.net, the WIT Colab notebooks).
These notebooks rebuild the *substance* of each activity locally so it actually runs.
"""

import nbformat as nbf
from pathlib import Path

HERE = Path(__file__).parent


def build(name, cells):
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }
    path = HERE / name
    nbf.write(nb, path)
    print(f"wrote {path}")


md = nbf.v4.new_markdown_cell
code = nbf.v4.new_code_cell


# ---------------------------------------------------------------- Activity 1
a1 = [
    md(
        "# Module 7 - Activity 1: Visually Probe ML Models (What-If Tool, rebuilt locally)\n"
        "\n"
        "**Brief:** run the Google What-If Tool (WIT) demos and probe a model without writing code.\n"
        "\n"
        "**Why this notebook:** the WIT demos are Colab-only and need `witwidget` + TensorFlow. Rather than\n"
        "fight the install, we rebuild WIT's five core probes in plain scikit-learn - the *ideas* are the\n"
        "assessable part, not the widget.\n"
        "\n"
        "We use the **wine quality** dataset, which is (a) the first WIT demo in the brief and (b) the same\n"
        "dataset as **Assessment 2** - so everything here is reusable there.\n"
        "\n"
        "| WIT feature | What it answers | Rebuilt here as |\n"
        "|---|---|---|\n"
        "| Model comparison | do two models agree? | LogReg vs Random Forest, side by side |\n"
        "| Datapoint editor | what if I change this feature? | manual perturbation of one wine |\n"
        "| **Counterfactuals** | what is the most similar wine the model judges *differently*? | nearest opposite-class neighbour |\n"
        "| Partial dependence | how does the model behave *overall*? | `PartialDependenceDisplay` (**global**) |\n"
        "| Performance & fairness | does the model fail on a *slice*? | per-bin accuracy table |\n"
        "| Threshold slider | what does moving the cut-off cost? | precision/recall sweep |\n"
    ),
    code(
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "from pathlib import Path\n"
        "\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.pipeline import make_pipeline\n"
        "from sklearn.preprocessing import StandardScaler\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.inspection import PartialDependenceDisplay\n"
        "from sklearn.metrics import (accuracy_score, roc_auc_score, confusion_matrix,\n"
        "                             precision_score, recall_score, f1_score)\n"
        "\n"
        "SEED = 42\n"
        "np.random.seed(SEED)\n"
        "OUT = Path('outputs'); OUT.mkdir(exist_ok=True)\n"
        "\n"
        "WINE = Path('../../../assignments/Assessment2/dataset/winequality-red.csv')\n"
        "df = pd.read_csv(WINE, sep=';')\n"
        "df.columns = [c.strip().replace(' ', '_') for c in df.columns]\n"
        "\n"
        "# Binary target, same framing as Assessment 2: is this a 'good' wine?\n"
        "df['good'] = (df['quality'] >= 7).astype(int)\n"
        "X = df.drop(columns=['quality', 'good'])\n"
        "y = df['good']\n"
        "\n"
        "print(f'{df.shape[0]} wines, {X.shape[1]} features')\n"
        "print(f\"class balance -> good: {y.mean():.1%}  (imbalanced, note it)\")\n"
        "X.head(3)"
    ),
    md(
        "## Probe 0 - Model comparison\n"
        "\n"
        "WIT's headline demo compares a **shallow** (scikit-learn) and a **deep** (Keras) model on the same\n"
        "data. We compare an **intrinsically interpretable** model (logistic regression - you can read its\n"
        "coefficients) against a **black box** (random forest - you cannot). That contrast *is* Module 7:\n"
        "the accuracy you gain from the black box is exactly the explainability you lose."
    ),
    code(
        "X_tr, X_te, y_tr, y_te = train_test_split(\n"
        "    X, y, test_size=0.25, random_state=SEED, stratify=y)\n"
        "\n"
        "logreg = make_pipeline(StandardScaler(),\n"
        "                       LogisticRegression(max_iter=2000, random_state=SEED))\n"
        "rf = RandomForestClassifier(n_estimators=300, random_state=SEED, n_jobs=-1)\n"
        "\n"
        "models = {'LogReg (intrinsic)': logreg, 'RandomForest (black box)': rf}\n"
        "rows = []\n"
        "for name, m in models.items():\n"
        "    m.fit(X_tr, y_tr)\n"
        "    p = m.predict(X_te)\n"
        "    proba = m.predict_proba(X_te)[:, 1]\n"
        "    rows.append({'model': name,\n"
        "                 'accuracy': accuracy_score(y_te, p),\n"
        "                 'roc_auc': roc_auc_score(y_te, proba),\n"
        "                 'recall(good)': recall_score(y_te, p),\n"
        "                 'precision(good)': precision_score(y_te, p, zero_division=0)})\n"
        "\n"
        "scores = pd.DataFrame(rows).set_index('model').round(3)\n"
        "print(scores.to_string())\n"
        "\n"
        "# Where do the two models DISAGREE? That is WIT's most useful view.\n"
        "pl = logreg.predict(X_te); pr = rf.predict(X_te)\n"
        "disagree = np.where(pl != pr)[0]\n"
        "print(f'\\nThe two models disagree on {len(disagree)}/{len(X_te)} test wines '\n"
        "      f'({len(disagree)/len(X_te):.1%}).')\n"
        "print('An accuracy number hides this. WIT shows it. So does one line of numpy.')"
    ),
    md(
        "## Probe 1 - Datapoint editor: *what if?*\n"
        "\n"
        "The tool's namesake. Take one wine, change one feature, watch the prediction move.\n"
        "This is a **local** probe - it says nothing about the model overall, only about this bottle."
    ),
    code(
        "i = 7  # one test wine\n"
        "wine = X_te.iloc[[i]].copy()\n"
        "base = rf.predict_proba(wine)[0, 1]\n"
        "print(f'Original wine -> P(good) = {base:.3f}   (actual: {\"good\" if y_te.iloc[i] else \"not good\"})')\n"
        "print()\n"
        "\n"
        "# Nudge each feature by +1 standard deviation and see what the model does.\n"
        "deltas = []\n"
        "for feat in X.columns:\n"
        "    edited = wine.copy()\n"
        "    edited[feat] = edited[feat] + X[feat].std()\n"
        "    deltas.append({'feature': feat,\n"
        "                   'original': wine[feat].values[0],\n"
        "                   'edited (+1 sd)': edited[feat].values[0],\n"
        "                   'new P(good)': rf.predict_proba(edited)[0, 1],\n"
        "                   'change': rf.predict_proba(edited)[0, 1] - base})\n"
        "\n"
        "editor = pd.DataFrame(deltas).sort_values('change', ascending=False).round(3)\n"
        "print('What-if: +1 standard deviation on each feature, for THIS wine only')\n"
        "print(editor.to_string(index=False))"
    ),
    md(
        "## Probe 2 - Counterfactual: the nearest wine the model judges *differently*\n"
        "\n"
        "WIT's signature button. Find the **most similar** datapoint that the model puts in the **other**\n"
        "class, then diff them. Whatever differs is what the decision actually hinged on.\n"
        "\n"
        "This is the same intuition as **CEM / pertinent negatives** in Activity 2, and it is the most\n"
        "human-legible explanation in the whole module: *\"this wine, but with more alcohol, would be good.\"*"
    ),
    code(
        "scaler = StandardScaler().fit(X_tr)\n"
        "Z_tr = scaler.transform(X_tr)\n"
        "\n"
        "z_wine = scaler.transform(wine)\n"
        "pred_wine = rf.predict(wine)[0]\n"
        "\n"
        "# candidates the model puts in the OPPOSITE class\n"
        "pred_tr = rf.predict(X_tr)\n"
        "mask = pred_tr != pred_wine\n"
        "dist = np.linalg.norm(Z_tr[mask] - z_wine, axis=1)\n"
        "cf_idx = np.where(mask)[0][dist.argmin()]\n"
        "cf = X_tr.iloc[[cf_idx]]\n"
        "\n"
        "cmp = pd.DataFrame({\n"
        "    'this wine': wine.iloc[0],\n"
        "    'counterfactual': cf.iloc[0],\n"
        "}).assign(difference=lambda d: d['counterfactual'] - d['this wine']).round(3)\n"
        "cmp['|diff| in sd'] = (cmp['difference'].abs() / X.std()).round(2)\n"
        "\n"
        "print(f'This wine    -> model says: {\"GOOD\" if pred_wine else \"not good\"} '\n"
        "      f'(P={base:.3f})')\n"
        "print(f'Nearest wine the model judges the OPPOSITE way -> '\n"
        "      f'{\"GOOD\" if not pred_wine else \"not good\"} '\n"
        "      f'(P={rf.predict_proba(cf)[0,1]:.3f})\\n')\n"
        "print(cmp.sort_values('|diff| in sd', ascending=False).to_string())\n"
        "print('\\nRead the top rows: those are the features that flip the verdict.')"
    ),
    md(
        "## Probe 3 - Partial dependence: the model's behaviour *overall*\n"
        "\n"
        "Now we zoom out. PDP answers **\"as alcohol rises, what happens to the average prediction?\"** -\n"
        "a statement about the whole model, not one wine.\n"
        "\n"
        "> **This is the global/local line you must be able to draw in the exam.**\n"
        "> Probes 1-2 were **local** (one bottle). Probe 3 is **global** (the model's average behaviour)."
    ),
    code(
        "top = ['alcohol', 'volatile_acidity', 'sulphates', 'total_sulfur_dioxide']\n"
        "fig, ax = plt.subplots(1, 4, figsize=(16, 3.4), constrained_layout=True)\n"
        "PartialDependenceDisplay.from_estimator(\n"
        "    rf, X_te, features=top, ax=ax, line_kw={'color': '#c0392b', 'lw': 2})\n"
        "for a in ax:\n"
        "    a.set_ylabel('P(good)')\n"
        "fig.suptitle('Partial dependence - GLOBAL: how the average prediction moves with each feature',\n"
        "             fontsize=11)\n"
        "fig.savefig(OUT / 'a1_partial_dependence.png', dpi=130, bbox_inches='tight')\n"
        "print('saved outputs/a1_partial_dependence.png')\n"
        "plt.show()"
    ),
    md(
        "## Probe 4 - Performance & fairness: does the model fail on a *slice*?\n"
        "\n"
        "WIT's fairness tab exists because **one accuracy number lies**. Slice the test set and the same\n"
        "model can be excellent on one group and useless on another. The wine data has no protected\n"
        "attribute, so we slice by alcohol - but the mechanic is exactly what you would run on\n"
        "`sex` or `race` in the COMPAS demo, and exactly what the NZ Algorithm Charter (Sowden) is about."
    ),
    code(
        "sl = X_te.copy()\n"
        "sl['y_true'] = y_te.values\n"
        "sl['y_pred'] = rf.predict(X_te)\n"
        "sl['bin'] = pd.qcut(sl['alcohol'], 4, labels=['low', 'mid-low', 'mid-high', 'high'])\n"
        "\n"
        "rows = []\n"
        "for b, g in sl.groupby('bin', observed=True):\n"
        "    rows.append({'alcohol slice': b, 'n': len(g),\n"
        "                 'actually good': int(g['y_true'].sum()),\n"
        "                 'accuracy': accuracy_score(g['y_true'], g['y_pred']),\n"
        "                 'recall(good)': recall_score(g['y_true'], g['y_pred'], zero_division=0)})\n"
        "\n"
        "slices = pd.DataFrame(rows).round(3)\n"
        "print(f\"Overall accuracy: {accuracy_score(sl['y_true'], sl['y_pred']):.3f}\\n\")\n"
        "print(slices.to_string(index=False))\n"
        "print('\\nThe headline accuracy is an average over slices that behave very differently.')"
    ),
    md(
        "## Probe 5 - Threshold slider: the cut-off is a *policy choice*, not a fact\n"
        "\n"
        "The model outputs a probability. Turning it into a yes/no needs a threshold, and 0.5 is a\n"
        "convention, not a truth. Moving it trades **precision against recall** - and *someone* has to\n"
        "decide which error is worse. That decision is a business/ethics call, not a maths one."
    ),
    code(
        "proba = rf.predict_proba(X_te)[:, 1]\n"
        "ts = np.linspace(0.05, 0.95, 91)\n"
        "prec = [precision_score(y_te, proba >= t, zero_division=0) for t in ts]\n"
        "rec = [recall_score(y_te, proba >= t, zero_division=0) for t in ts]\n"
        "f1 = [f1_score(y_te, proba >= t, zero_division=0) for t in ts]\n"
        "\n"
        "best_t = ts[int(np.argmax(f1))]\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 4.2))\n"
        "ax.plot(ts, prec, label='precision', lw=2)\n"
        "ax.plot(ts, rec, label='recall', lw=2)\n"
        "ax.plot(ts, f1, label='F1', lw=2, ls='--', color='#c0392b')\n"
        "ax.axvline(0.5, color='grey', ls=':', label='default 0.5')\n"
        "ax.axvline(best_t, color='green', ls=':', label=f'best F1 @ {best_t:.2f}')\n"
        "ax.set_xlabel('decision threshold'); ax.set_ylabel('score')\n"
        "ax.set_title('Threshold slider - precision/recall is a trade you choose')\n"
        "ax.legend(); ax.grid(alpha=.3)\n"
        "fig.savefig(OUT / 'a1_threshold_sweep.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()\n"
        "\n"
        "for t in (0.5, best_t):\n"
        "    tn, fp, fn, tp = confusion_matrix(y_te, proba >= t).ravel()\n"
        "    print(f'threshold {t:.2f} -> TP={tp:3d} FP={fp:3d} FN={fn:3d} TN={tn:3d} | '\n"
        "          f'precision={precision_score(y_te, proba>=t, zero_division=0):.3f} '\n"
        "          f'recall={recall_score(y_te, proba>=t, zero_division=0):.3f}')"
    ),
    md(
        "## Discussion (the brief's questions)\n"
        "\n"
        "**\"Can the tool minimise the issues from running algorithms that affect humans?\"**\n"
        "Partly. It makes failure *visible* - the slice table (Probe 4) is how you catch a model that is\n"
        "95% accurate overall and 60% accurate on one group. But visibility is not a fix: WIT shows you the\n"
        "disparity, it does not tell you what is acceptable. That is the gap the **Algorithm Charter** and\n"
        "the **Data Ethics Advisory Group** (Sowden, Res. 5) exist to fill.\n"
        "\n"
        "**\"Do you need special expertise to read the outputs?\"**\n"
        "To *read* them, no - the counterfactual (Probe 2) is plain English: *this wine, with more alcohol,\n"
        "flips to good*. To *not be misled* by them, yes. A PDP assumes features move independently; when\n"
        "they are correlated it draws a curve over wines that could never exist. That is Aha's warning\n"
        "(Res. 4) in practice: **a confident wrong explanation is worse than no explanation.**\n"
        "\n"
        "**Carry into Assessment 2:** Probe 0 (model comparison + disagreement count), Probe 4 (slice table)\n"
        "and Probe 5 (threshold choice) are all directly reusable in the A2 evaluation section."
    ),
]


# ---------------------------------------------------------------- Activity 2
a2 = [
    md(
        "# Module 7 - Activity 2: Bank Loan Explainability (AI Explainability 360, rebuilt locally)\n"
        "\n"
        "**Brief:** work through the IBM AIX360 bank-loan demo; see what explanation each *consumer type*\n"
        "needs (data scientist, loan officer, bank customer); explore the **CEM** and **Protodash** explainers.\n"
        "Then answer: *if the bank were legally obliged to explain every rejection, could you?*\n"
        "\n"
        "**Why this notebook:** `aix360.mybluemix.net` is dead and the HELOC dataset needs registration.\n"
        "We use **German Credit** (`credit-g`, 1,000 real loan applications) and implement the two explainers\n"
        "from scratch - which is the point, because it forces you to see what they actually *do*.\n"
        "\n"
        "### The one idea of AIX360\n"
        "> **One decision. Four audiences. Four different explanations. No single explanation serves all.**\n"
        "\n"
        "| Audience | The question they are actually asking | Explainer | Scope |\n"
        "|---|---|---|---|\n"
        "| **Loan officer** | \"what drives approvals in general?\" | interpretable model (rules/coefficients) | **global** |\n"
        "| **Rejected customer** | \"what would I have to change?\" | **CEM** (pertinent negative) | **local** |\n"
        "| **Data scientist** | \"which features drove *this* score?\" | **SHAP** | **local + global** |\n"
        "| **Regulator / adjudicator** | \"is this decision consistent with precedent?\" | **Protodash** (prototypes) | **local** |\n"
    ),
    code(
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "from pathlib import Path\n"
        "\n"
        "from sklearn.datasets import fetch_openml\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.tree import DecisionTreeClassifier, export_text\n"
        "from sklearn.preprocessing import StandardScaler\n"
        "from sklearn.metrics import accuracy_score, roc_auc_score\n"
        "\n"
        "SEED = 42\n"
        "np.random.seed(SEED)\n"
        "OUT = Path('outputs'); OUT.mkdir(exist_ok=True)\n"
        "DATA = Path('dataset'); DATA.mkdir(exist_ok=True)\n"
        "\n"
        "cache = DATA / 'german_credit.csv'\n"
        "if cache.exists():\n"
        "    raw = pd.read_csv(cache)\n"
        "else:\n"
        "    raw = fetch_openml('credit-g', version=1, as_frame=True).frame\n"
        "    raw.to_csv(cache, index=False)\n"
        "\n"
        "# target: 'good' = repaid = APPROVE, 'bad' = defaulted = REJECT\n"
        "raw['approved'] = (raw['class'] == 'good').astype(int)\n"
        "y = raw['approved']\n"
        "X_raw = raw.drop(columns=['class', 'approved'])\n"
        "X = pd.get_dummies(X_raw, drop_first=True).astype(float)\n"
        "\n"
        "print(f'{len(raw)} loan applications, {X.shape[1]} encoded features')\n"
        "print(f'approval rate: {y.mean():.1%}')\n"
        "X_raw.head(3)"
    ),
    code(
        "X_tr, X_te, y_tr, y_te = train_test_split(\n"
        "    X, y, test_size=0.25, random_state=SEED, stratify=y)\n"
        "\n"
        "# The bank's production model: accurate, opaque.\n"
        "model = RandomForestClassifier(n_estimators=400, random_state=SEED, n_jobs=-1)\n"
        "model.fit(X_tr, y_tr)\n"
        "print(f'accuracy: {accuracy_score(y_te, model.predict(X_te)):.3f}')\n"
        "print(f'roc_auc : {roc_auc_score(y_te, model.predict_proba(X_te)[:,1]):.3f}')\n"
        "print('\\nThis model decides who gets a loan. It cannot explain itself. That is the problem.')"
    ),
    md(
        "## Audience 1 - The loan officer: a **global**, **intrinsic** explanation\n"
        "\n"
        "The officer does not want a per-customer heat map. They want the bank's *policy* in their head:\n"
        "what generally gets you approved. So we do not explain the black box at all - we **replace it**\n"
        "with a model that is transparent by design (Molnar's intrinsic route). The cost is a little accuracy.\n"
        "That cost is the module's central trade-off, priced explicitly."
    ),
    code(
        "# A) coefficients: readable effect per feature\n"
        "sc = StandardScaler().fit(X_tr)\n"
        "lr = LogisticRegression(max_iter=3000, random_state=SEED).fit(sc.transform(X_tr), y_tr)\n"
        "print(f'LogReg  accuracy {accuracy_score(y_te, lr.predict(sc.transform(X_te))):.3f} '\n"
        "      f'| roc_auc {roc_auc_score(y_te, lr.predict_proba(sc.transform(X_te))[:,1]):.3f}')\n"
        "\n"
        "coef = pd.Series(lr.coef_[0], index=X.columns).sort_values()\n"
        "print('\\n--- Pushes you toward REJECTION ---')\n"
        "print(coef.head(6).round(3).to_string())\n"
        "print('\\n--- Pushes you toward APPROVAL ---')\n"
        "print(coef.tail(6).round(3).to_string()[::1])\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 5))\n"
        "top = pd.concat([coef.head(8), coef.tail(8)])\n"
        "ax.barh(top.index, top.values,\n"
        "        color=['#c0392b' if v < 0 else '#27ae60' for v in top.values])\n"
        "ax.axvline(0, color='k', lw=.8)\n"
        "ax.set_title('Loan officer view - GLOBAL: what drives approval (logistic coefficients)')\n"
        "ax.set_xlabel('<- rejection      coefficient      approval ->')\n"
        "fig.savefig(OUT / 'a2_global_coefficients.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()"
    ),
    code(
        "# B) the same policy as RULES - what a loan officer can actually carry in their head\n"
        "tree = DecisionTreeClassifier(max_depth=3, random_state=SEED).fit(X_tr, y_tr)\n"
        "print(f'Depth-3 tree accuracy: {accuracy_score(y_te, tree.predict(X_te)):.3f}\\n')\n"
        "print(export_text(tree, feature_names=list(X.columns), max_depth=3))\n"
        "print('That is the whole model. A human can audit it. That is what \"intrinsic\" buys you.')"
    ),
    md(
        "## Audience 2 - The rejected customer: **CEM** (contrastive / *pertinent negative*)\n"
        "\n"
        "This is the explanation that actually matters to a human being, and it is the one banks are worst at.\n"
        "The customer does not want feature importances. They want:\n"
        "\n"
        "> **\"What is the smallest change that would have got me approved?\"**\n"
        "\n"
        "That is CEM's *pertinent negative*: the minimal perturbation that flips the decision. We search for\n"
        "it directly over the **actionable** features - because telling someone to change their age is not\n"
        "an explanation, it is an insult."
    ),
    code(
        "# find a rejected applicant\n"
        "pred_te = model.predict(X_te)\n"
        "rejected_pos = np.where(pred_te == 0)[0][3]\n"
        "applicant = X_te.iloc[[rejected_pos]]\n"
        "p0 = model.predict_proba(applicant)[0, 1]\n"
        "print(f'Applicant #{X_te.index[rejected_pos]} -> P(approve) = {p0:.3f}  ==> REJECTED\\n')\n"
        "\n"
        "orig = X_raw.loc[X_te.index[rejected_pos]]\n"
        "print(orig[['duration', 'credit_amount', 'savings_status', 'checking_status',\n"
        "            'employment', 'age', 'purpose']].to_string())"
    ),
    code(
        "# CEM-style search: which single ACTIONABLE change flips the decision?\n"
        "# Actionable = the applicant could plausibly alter it. Age/sex/foreign_worker are NOT.\n"
        "ACTIONABLE = ['duration', 'credit_amount', 'installment_commitment',\n"
        "              'existing_credits', 'num_dependents', 'residence_since']\n"
        "\n"
        "results = []\n"
        "for feat in ACTIONABLE:\n"
        "    lo, hi = X[feat].quantile([0.02, 0.98])\n"
        "    for val in np.linspace(lo, hi, 60):\n"
        "        cand = applicant.copy()\n"
        "        cand[feat] = val\n"
        "        p = model.predict_proba(cand)[0, 1]\n"
        "        if p >= 0.5:\n"
        "            results.append({'change': feat,\n"
        "                            'from': applicant[feat].values[0],\n"
        "                            'to': round(val, 1),\n"
        "                            'P(approve)': round(p, 3),\n"
        "                            'effort (|sd|)': round(abs(val - applicant[feat].values[0])\n"
        "                                                   / X[feat].std(), 2)})\n"
        "            break\n"
        "\n"
        "if results:\n"
        "    cem = pd.DataFrame(results).sort_values('effort (|sd|)')\n"
        "    print('PERTINENT NEGATIVES - single changes that flip REJECTED -> APPROVED:\\n')\n"
        "    print(cem.to_string(index=False))\n"
        "    best = cem.iloc[0]\n"
        "    print(f\"\\n>> The explanation you give the customer:\\n\"\n"
        "          f\"   'Your application was declined. Had your {best['change']} been \"\n"
        "          f\"{best['to']} instead of {best['from']}, it would have been approved.'\")\n"
        "else:\n"
        "    print('No single actionable change flips this decision - the rejection is over-determined.')\n"
        "    print('That is itself an important (and honest) explanation to give.')"
    ),
    md(
        "## Audience 3 - The data scientist: **SHAP** (local attribution)\n"
        "\n"
        "The DS does not want a counterfactual, they want the **decomposition**: how much did each feature\n"
        "contribute to *this* score, and do those contributions sum to the prediction? That is exactly what\n"
        "Shapley values guarantee (Molnar Ch. 4)."
    ),
    code(
        "import shap\n"
        "\n"
        "explainer = shap.TreeExplainer(model)\n"
        "sv = explainer(X_te)\n"
        "sv_pos = sv[..., 1] if sv.values.ndim == 3 else sv  # binary RF -> two output dims\n"
        "\n"
        "one = sv_pos[rejected_pos]\n"
        "contrib = pd.DataFrame({'feature': X.columns, 'shap': one.values}) \\\n"
        "            .assign(absv=lambda d: d.shap.abs()) \\\n"
        "            .sort_values('absv', ascending=False).head(10)\n"
        "\n"
        "print(f'base rate (avg applicant): {one.base_values:.3f}')\n"
        "print(f'this applicant           : {one.base_values + one.values.sum():.3f}\\n')\n"
        "print('Top contributions to THIS rejection (negative = pushed toward reject):')\n"
        "print(contrib[['feature', 'shap']].round(3).to_string(index=False))\n"
        "\n"
        "plt.figure()\n"
        "shap.plots.waterfall(one, max_display=12, show=False)\n"
        "plt.title('Data scientist view - LOCAL: SHAP for this one rejection', fontsize=10)\n"
        "plt.savefig(OUT / 'a2_shap_waterfall.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()"
    ),
    md(
        "## Audience 4 - The regulator: **Protodash** (explanation by precedent)\n"
        "\n"
        "Protodash answers a question no attribution method can: **\"show me the applicants most like this\n"
        "one, and what happened to them.\"** It explains by *precedent*, not by arithmetic - which is, not\n"
        "coincidentally, how law works.\n"
        "\n"
        "It greedily picks prototypes that best *represent* the target - here, the approved applicants most\n"
        "similar to our rejected one. If they look nearly identical, the bank has a consistency problem."
    ),
    code(
        "def protodash(target, candidates, k=3, gamma=None):\n"
        "    \"\"\"Greedy prototype selection with an RBF kernel (the core of Protodash).\n"
        "    Picks the k candidates that jointly best represent `target`.\"\"\"\n"
        "    if gamma is None:\n"
        "        gamma = 1.0 / candidates.shape[1]\n"
        "    d = np.linalg.norm(candidates - target, axis=1)\n"
        "    sim = np.exp(-gamma * d ** 2)          # similarity to the target\n"
        "    chosen, covered = [], np.zeros(len(candidates))\n"
        "    for _ in range(k):\n"
        "        gain = sim - covered               # marginal, so prototypes stay diverse\n"
        "        gain[chosen] = -np.inf\n"
        "        j = int(np.argmax(gain))\n"
        "        chosen.append(j)\n"
        "        dj = np.linalg.norm(candidates - candidates[j], axis=1)\n"
        "        covered = np.maximum(covered, np.exp(-gamma * dj ** 2) * sim[j])\n"
        "    return chosen\n"
        "\n"
        "sc_all = StandardScaler().fit(X_tr)\n"
        "approved_mask = (model.predict(X_tr) == 1)\n"
        "cand = sc_all.transform(X_tr[approved_mask])\n"
        "target = sc_all.transform(applicant)[0]\n"
        "\n"
        "proto_idx = protodash(target, cand, k=3)\n"
        "proto_rows = X_tr[approved_mask].iloc[proto_idx]\n"
        "\n"
        "show = ['duration', 'credit_amount', 'installment_commitment', 'age', 'existing_credits']\n"
        "table = pd.concat([applicant[show], proto_rows[show]])\n"
        "table.index = ['>> REJECTED applicant'] + [f'approved precedent {i+1}' for i in range(3)]\n"
        "table['P(approve)'] = model.predict_proba(pd.concat([applicant, proto_rows]))[:, 1].round(3)\n"
        "\n"
        "print('PROTODASH - the approved applicants most similar to our rejected one:\\n')\n"
        "print(table.round(1).to_string())\n"
        "print('\\nIf these look almost identical to the rejected applicant, the bank has a problem:')\n"
        "print('the decision boundary is doing something it cannot justify to a regulator.')"
    ),
    md(
        "## Discussion (the brief's question)\n"
        "\n"
        "**\"Assume the bank has a legal obligation to explain every rejection. Can you? What is missing?\"**\n"
        "\n"
        "We can now produce four true statements about the same rejection:\n"
        "\n"
        "1. *Globally*, short loan duration and a healthy checking balance drive approvals (coefficients/rules).\n"
        "2. *For you*, the biggest negative contributions were X, Y, Z (SHAP).\n"
        "3. *To flip it*, reduce the loan duration to N months (CEM pertinent negative).\n"
        "4. *For consistency*, here are 3 approved applicants who look like you (Protodash).\n"
        "\n"
        "**Only #3 is an explanation a human can act on.** The others are descriptions of a model, not\n"
        "reasons for a decision - which is precisely the gap the module is pointing at.\n"
        "\n"
        "**What is still missing, and it is a lot:**\n"
        "\n"
        "- **Explaining the model is not explaining the decision.** SHAP faithfully reports what the model\n"
        "  did. It is silent on whether the model *should* have done it. A model that learnt a proxy for a\n"
        "  protected attribute produces a beautiful, fully-legible, discriminatory explanation.\n"
        "- **The proxy problem is live in this dataset.** `personal_status` encodes sex and\n"
        "  `foreign_worker` is a protected class - both sit in the feature matrix and both are unactionable.\n"
        "  A counterfactual that says *\"be a different person\"* is not a remedy.\n"
        "- **Counterfactuals are not unique.** Several different single changes flip the decision (see the CEM\n"
        "  table). The bank picks which one to tell you. That choice is unaudited and unregulated.\n"
        "- **A confident wrong explanation is worse than none** (Aha, Res. 4). Give a customer an actionable\n"
        "  reason, have them act on it, and get rejected again - you have destroyed the trust you were\n"
        "  trying to build.\n"
        "\n"
        "This is exactly why Sowden (Res. 5) answers the trust problem with an **Algorithm Charter** and a\n"
        "**Data Ethics Advisory Group** rather than a better plotting library. **Explainability is a\n"
        "governance problem with a technical component - not a technical problem.**"
    ),
]


# ---------------------------------------------------------------- Activity 3
a3 = [
    md(
        "# Module 7 - Activity 3: SHAP + Explainer Dashboard (Titanic)\n"
        "\n"
        "**Brief:** interact with the Titanic explainer dashboard - feature importances, model performance,\n"
        "individual predictions, feature dependence - then discuss which features drive survival.\n"
        "\n"
        "**Why this notebook:** `titanicexplainer.herokuapp.com` is dead (Heroku killed free dynos in 2022).\n"
        "We rebuild the dashboard's four panels with SHAP directly - which is better anyway, because the\n"
        "dashboard is just a UI over exactly these calls.\n"
        "\n"
        "> **SHAP** (Lundberg 2017, on Shapley 1953): explain a prediction by computing **each feature's\n"
        "> contribution** to it. The contributions are additive: `base_value + sum(shap) = prediction`.\n"
        "> That additivity is what separates SHAP from every hand-wavy importance score.\n"
        "\n"
        "| Dashboard panel | Scope | SHAP call |\n"
        "|---|---|---|\n"
        "| Feature importances | **global** | `shap.plots.bar` |\n"
        "| Feature dependence | **global** | `shap.plots.scatter` |\n"
        "| Individual prediction | **local** | `shap.plots.waterfall` |\n"
        "| (all of it at once) | both | `shap.plots.beeswarm` |\n"
    ),
    code(
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "from pathlib import Path\n"
        "import shap\n"
        "\n"
        "from sklearn.datasets import fetch_openml\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix\n"
        "\n"
        "SEED = 42\n"
        "np.random.seed(SEED)\n"
        "OUT = Path('outputs'); OUT.mkdir(exist_ok=True)\n"
        "DATA = Path('dataset'); DATA.mkdir(exist_ok=True)\n"
        "\n"
        "cache = DATA / 'titanic.csv'\n"
        "if cache.exists():\n"
        "    raw = pd.read_csv(cache)\n"
        "else:\n"
        "    raw = fetch_openml('titanic', version=1, as_frame=True).frame\n"
        "    raw.to_csv(cache, index=False)\n"
        "\n"
        "raw['survived'] = raw['survived'].astype(int)\n"
        "print(f'{len(raw)} passengers | survival rate {raw.survived.mean():.1%}')\n"
        "raw.head(3)"
    ),
    md(
        "## Before any explaining: a leakage trap\n"
        "\n"
        "This dataset ships with a column called `boat` - the lifeboat number. If you were **in a lifeboat,\n"
        "you survived**. It is the outcome wearing a moustache.\n"
        "\n"
        "Leave it in and you get a near-perfect model that has learnt nothing. Worse for this module: SHAP\n"
        "will happily produce a **beautiful, confident, completely worthless explanation** of it. Let's prove\n"
        "it, because this is the single most useful thing in the notebook."
    ),
    code(
        "def prep(df, cols):\n"
        "    \"\"\"Encode to numeric for the tree model.\n"
        "\n"
        "    NB: test `is_numeric_dtype`, do NOT select on 'object'. fetch_openml returns\n"
        "    sex/embarked as *category* dtype, and a category column silently survives an\n"
        "    'object'-only filter -> pd.to_numeric coerces 'male' to NaN -> fillna(-1) makes\n"
        "    the column CONSTANT -> the model never sees sex at all. (Ask me how I know.)\n"
        "    \"\"\"\n"
        "    d = df[cols].copy()\n"
        "    for c in d.columns:\n"
        "        if not pd.api.types.is_numeric_dtype(d[c]):\n"
        "            d[c] = d[c].astype('category').cat.codes   # strings/categories -> int, NaN -> -1\n"
        "    return d.astype(float).fillna(-1)                  # numeric NaN (age) -> -1 sentinel\n"
        "\n"
        "y = raw['survived']\n"
        "leaky_cols = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'boat']\n"
        "clean_cols = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']\n"
        "\n"
        "for label, cols in [('WITH boat (leaky)', leaky_cols), ('WITHOUT boat (honest)', clean_cols)]:\n"
        "    Xc = prep(raw, cols)\n"
        "    xtr, xte, ytr, yte = train_test_split(Xc, y, test_size=.25,\n"
        "                                          random_state=SEED, stratify=y)\n"
        "    m = RandomForestClassifier(n_estimators=300, random_state=SEED, n_jobs=-1).fit(xtr, ytr)\n"
        "    auc = roc_auc_score(yte, m.predict_proba(xte)[:, 1])\n"
        "    acc = accuracy_score(yte, m.predict(xte))\n"
        "    print(f'{label:24s} accuracy={acc:.3f}  roc_auc={auc:.3f}')\n"
        "\n"
        "print('\\nThe leaky model looks brilliant and is useless: at prediction time (the ship is sinking)')\n"
        "print('nobody knows their lifeboat number yet. Drop it - along with body/name/ticket/cabin.')"
    ),
    code(
        "X = prep(raw, clean_cols)\n"
        "\n"
        "# Guard rail: a constant column is a silently broken feature. Fail loudly instead.\n"
        "dead = list(X.columns[X.nunique() <= 1])\n"
        "assert not dead, f'constant (= broken) column(s): {dead}'\n"
        "print('encoded feature check - unique values per column:')\n"
        "print(X.nunique().to_string())\n"
        "\n"
        "X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=.25,\n"
        "                                          random_state=SEED, stratify=y)\n"
        "\n"
        "model = RandomForestClassifier(n_estimators=400, max_depth=6,\n"
        "                               random_state=SEED, n_jobs=-1).fit(X_tr, y_tr)\n"
        "\n"
        "pred = model.predict(X_te)\n"
        "print('=== Panel: model performance ===')\n"
        "print(f'accuracy {accuracy_score(y_te, pred):.3f} | '\n"
        "      f'roc_auc {roc_auc_score(y_te, model.predict_proba(X_te)[:,1]):.3f}\\n')\n"
        "tn, fp, fn, tp = confusion_matrix(y_te, pred).ravel()\n"
        "print(pd.DataFrame([[tn, fp], [fn, tp]],\n"
        "                   index=['actual: died', 'actual: survived'],\n"
        "                   columns=['pred: died', 'pred: survived']).to_string())\n"
        "\n"
        "# sex was label-encoded: remember the mapping so we can read the plots\n"
        "sex_codes = dict(enumerate(raw['sex'].astype('category').cat.categories))\n"
        "print(f'\\n(encoding: sex -> {sex_codes})')"
    ),
    code(
        "explainer = shap.TreeExplainer(model)\n"
        "sv = explainer(X_te)\n"
        "sv = sv[..., 1] if sv.values.ndim == 3 else sv   # keep the P(survived) output\n"
        "print(f'SHAP values: {sv.values.shape}  (rows x features)')\n"
        "print(f'base value (average prediction): {sv.base_values[0]:.3f}')\n"
        "\n"
        "# The additivity guarantee - check it yourself, do not take it on faith\n"
        "i = 0\n"
        "recon = sv.base_values[i] + sv.values[i].sum()\n"
        "actual = model.predict_proba(X_te.iloc[[i]])[0, 1]\n"
        "print(f'\\nbase + sum(shap) = {recon:.4f}')\n"
        "print(f'model prediction = {actual:.4f}   <- they match. That is the Shapley guarantee.')"
    ),
    md(
        "## Panel 1 - Feature importances (**GLOBAL**)\n"
        "\n"
        "Mean absolute SHAP per feature: *across all passengers*, how much did this feature move predictions?\n"
        "\n"
        "> ⚠️ **This is the global side of the exam distinction.** It tells you nothing about any individual."
    ),
    code(
        "plt.figure()\n"
        "shap.plots.bar(sv, max_display=8, show=False)\n"
        "plt.title('Panel 1 - GLOBAL feature importance (mean |SHAP|)', fontsize=11)\n"
        "plt.savefig(OUT / 'a3_global_importance.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()\n"
        "\n"
        "imp = pd.Series(np.abs(sv.values).mean(0), index=X.columns).sort_values(ascending=False)\n"
        "print(imp.round(4).to_string())"
    ),
    md(
        "## Panel 2 - Beeswarm: importance **and direction**\n"
        "\n"
        "The bar chart says *sex matters most*. It does not say **which sex**. The beeswarm does: every dot\n"
        "is a passenger, colour is the feature's value, x-position is its SHAP contribution."
    ),
    code(
        "plt.figure()\n"
        "shap.plots.beeswarm(sv, max_display=8, show=False)\n"
        "plt.title('Panel 2 - beeswarm: each dot is a passenger', fontsize=11)\n"
        "plt.savefig(OUT / 'a3_beeswarm.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(f'sex encoding: {sex_codes}  ->  low (blue) = female, high (red) = male')\n"
        "print('Read it: blue sex dots sit far RIGHT (positive SHAP = pushed toward survival).\\n')\n"
        "\n"
        "s = sv.values[:, list(X.columns).index('sex')]\n"
        "print(f'mean SHAP(sex) | female: {s[X_te[\"sex\"] == 0].mean():+.3f}   '\n"
        "      f'male: {s[X_te[\"sex\"] == 1].mean():+.3f}')\n"
        "print('The bar chart could only tell you sex MATTERED. The beeswarm tells you WHICH WAY.')"
    ),
    md(
        "## Panel 3 - Individual predictions (**LOCAL**) ⭐\n"
        "\n"
        "> **This is the local side of the exam distinction - and the whole reason SHAP exists.**\n"
        "> Same model, same SHAP machinery, but now: *why did the model say THIS about THIS passenger?*\n"
        "\n"
        "The waterfall starts at the base value (the average passenger) and each feature pushes the\n"
        "prediction up or down until it lands on this passenger's score."
    ),
    code(
        "proba = model.predict_proba(X_te)[:, 1]\n"
        "hi = int(np.argmax(proba))   # most confident survivor\n"
        "lo = int(np.argmin(proba))   # most confident death\n"
        "\n"
        "for tag, idx in [('MOST LIKELY TO SURVIVE', hi), ('LEAST LIKELY TO SURVIVE', lo)]:\n"
        "    row = raw.loc[X_te.index[idx]]\n"
        "    print(f'--- {tag} ---')\n"
        "    print(f\"  {row['name']}\")\n"
        "    print(f\"  {row['sex']}, age {row['age']}, class {row['pclass']}, fare {row['fare']:.1f}\")\n"
        "    print(f\"  model P(survived) = {proba[idx]:.3f}  |  actually survived: \"\n"
        "          f\"{'YES' if row['survived'] else 'NO'}\\n\")"
    ),
    code(
        "for tag, idx, fname in [('survivor', hi, 'a3_local_survivor.png'),\n"
        "                        ('victim', lo, 'a3_local_victim.png')]:\n"
        "    plt.figure()\n"
        "    shap.plots.waterfall(sv[idx], max_display=8, show=False)\n"
        "    name = raw.loc[X_te.index[idx], 'name'][:42]\n"
        "    plt.title(f'Panel 3 - LOCAL: why the model predicted this for {name}', fontsize=10)\n"
        "    plt.savefig(OUT / fname, dpi=130, bbox_inches='tight')\n"
        "    plt.show()\n"
        "\n"
        "print('Same model. Same SHAP. Two completely different explanations.')\n"
        "print('THAT is what \"local\" means - and why a global importance bar could never tell you this.')"
    ),
    md(
        "## Panel 4 - Feature dependence: how one feature's effect *varies*\n"
        "\n"
        "A single number for 'age importance' hides that age helps the young and hurts the old - and that\n"
        "its effect **depends on sex**. Dependence plots expose that interaction."
    ),
    code(
        "fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))\n"
        "shap.plots.scatter(sv[:, 'age'], color=sv[:, 'sex'], ax=axes[0], show=False)\n"
        "axes[0].set_title('age (coloured by sex)', fontsize=10)\n"
        "shap.plots.scatter(sv[:, 'pclass'], color=sv[:, 'fare'], ax=axes[1], show=False)\n"
        "axes[1].set_title('pclass (coloured by fare)', fontsize=10)\n"
        "fig.suptitle('Panel 4 - feature dependence: effects are not constant', fontsize=11)\n"
        "fig.tight_layout()\n"
        "fig.savefig(OUT / 'a3_dependence.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()\n"
        "\n"
        "# Quantify the age effect rather than eyeballing the scatter (-1 = imputed missing age)\n"
        "age = X_te['age'].values\n"
        "a_shap = sv.values[:, list(X.columns).index('age')]\n"
        "real = age >= 0\n"
        "band = pd.cut(age[real], [0, 12, 18, 35, 60, 100])\n"
        "print('mean SHAP(age) by age band - real ages only:')\n"
        "print(pd.Series(a_shap[real]).groupby(band, observed=True)\n"
        "        .agg(['mean', 'count']).round(4).to_string())\n"
        "print('\\nDirection is right: children get a positive push, it decays monotonically with age.')\n"
        "print('But look at the MAGNITUDE (~0.05) next to sex (~0.26). See the discussion below.')"
    ),
    md(
        "## Discussion (the brief's questions)\n"
        "\n"
        "**\"Which parameters matter most for survival?\"**\n"
        "`sex` dominates and it is not close - mean |SHAP| ~0.18 against ~0.07 for the next feature. Being\n"
        "female adds **+0.26** to the predicted survival probability; being male subtracts **0.14**. Then come\n"
        "`pclass` and `fare` - the same thing wearing two hats: **wealth**.\n"
        "\n"
        "The interesting part is what the numbers *refuse* to say. The folk summary is *\"women and children\n"
        "first\"*, but `age` ranks **6th of 7** (mean |SHAP| 0.020). Its *direction* is right - binning the\n"
        "SHAP values by age band gives children (0-12) **+0.051** and the elderly (60+) **-0.062**, a clean\n"
        "monotone decay - but its *magnitude* is small. What the model actually learnt from the data is\n"
        "**\"women first, money second, children a distant third\"**.\n"
        "\n"
        "That gap between the story you expected and the numbers you got is the entire value of SHAP. A\n"
        "narrative would have sailed straight past it.\n"
        "\n"
        "**\"What is the relationship between features and output?\"**\n"
        "Not linear and not independent - Panel 4 shows age's effect **depends on** sex. This is exactly why\n"
        "a single importance number is not an explanation.\n"
        "\n"
        "**\"Should consumers have a dashboard whenever an ML decision affects them?\"**\n"
        "The honest answer from this notebook is *yes, but a dashboard is not enough*:\n"
        "\n"
        "- The **leakage demo** is the argument. A model trained on `boat` scores ~0.97 AUC and SHAP explains\n"
        "  it *fluently*. The explanation would be confident, well-rendered, and worthless. **A dashboard\n"
        "  cannot tell you the model is asking the wrong question** - that is Aha's \"a wrong explanation is\n"
        "  worse than none\" (Res. 4), demonstrated rather than asserted.\n"
        "- SHAP explains **what the model did**, never **whether it should have**. Here the top feature is\n"
        "  `sex`. On the Titanic that is history. In a loan model it is a lawsuit.\n"
        "\n"
        "So: ship the dashboard, but ship it *with* the governance around it (Sowden, Res. 5). The\n"
        "explanation is the deliverable; the accountability for it is the point.\n"
        "\n"
        "---\n"
        "\n"
        "### The one table to remember\n"
        "\n"
        "| | **Global** (the model) | **Local** (one prediction) |\n"
        "|---|---|---|\n"
        "| **Question** | what does it do in general? | why did it say *this*, about *me*? |\n"
        "| **Method** | `shap.plots.bar`, beeswarm, permutation importance, PDP | `shap.plots.waterfall`, LIME, counterfactual/CEM |\n"
        "| **Panel** | 1, 2, 4 | 3 |\n"
        "| **Audience** | the modeller, the auditor | the person the decision happened to |\n"
        "\n"
        "**Carry into Assessment 2:** Panels 1-3 on your wine classifier turn the evaluation section from\n"
        "*\"the model got 0.89\"* into *\"the model got 0.89, and here is what it learnt, and here is why it\n"
        "misjudged this particular wine.\"* That is the difference between a pass and a distinction."
    ),
]


# ---------------------------------------------------------------- Activity 4
a4 = [
    md(
        "# Module 7 - Activity 4: Eli5, LIME and Mlxtend\n"
        "\n"
        "**Brief:** run the three packages - **Eli5** (\"explain like I'm 5\"), **LIME** (local surrogate) and\n"
        "**Mlxtend** (decision boundaries). Inspect feature importances, interpret predictions, look at\n"
        "decision regions. Then: *how do these compare with the explainer dashboard?*\n"
        "\n"
        "**The question worth actually asking.** Running three tools that each print a bar chart is busywork.\n"
        "The real experiment is to point **all of them at the same prediction** and check whether they\n"
        "**agree**. Because if two explanations of one decision contradict each other, at most one is right -\n"
        "and nothing on the screen tells you which.\n"
        "\n"
        "> That is Aha's *\"a wrong explanation is worse than none\"* (Res. 4) turned into an experiment.\n"
        "\n"
        "We reuse the **wine** data (Assessment 2) and one random forest throughout, so every difference we\n"
        "see comes from the **explainer**, not the model.\n"
        "\n"
        "**Spoiler, so you know what you are looking for:** they do not agree. One of these libraries hands us\n"
        "a fluent, well-formatted explanation with **every sign backwards** - it reports that a wine's vinegar\n"
        "taint is what made it *good*. We catch it not with a better chart, but by going back and\n"
        "**intervening on the model itself**. That habit is the actual deliverable of this notebook."
    ),
    code(
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "from pathlib import Path\n"
        "\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.metrics import accuracy_score, roc_auc_score\n"
        "from scipy.stats import spearmanr\n"
        "\n"
        "SEED = 42\n"
        "np.random.seed(SEED)\n"
        "OUT = Path('outputs'); OUT.mkdir(exist_ok=True)\n"
        "\n"
        "WINE = Path('../../../assignments/Assessment2/dataset/winequality-red.csv')\n"
        "df = pd.read_csv(WINE, sep=';')\n"
        "df.columns = [c.strip().replace(' ', '_') for c in df.columns]\n"
        "df['good'] = (df['quality'] >= 7).astype(int)\n"
        "\n"
        "X = df.drop(columns=['quality', 'good'])\n"
        "y = df['good']\n"
        "FEATS = list(X.columns)\n"
        "\n"
        "X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=.25,\n"
        "                                          random_state=SEED, stratify=y)\n"
        "model = RandomForestClassifier(n_estimators=300, random_state=SEED, n_jobs=-1).fit(X_tr, y_tr)\n"
        "print(f'accuracy {accuracy_score(y_te, model.predict(X_te)):.3f} | '\n"
        "      f'roc_auc {roc_auc_score(y_te, model.predict_proba(X_te)[:,1]):.3f}')\n"
        "print('One model. Four explainers. Do they tell the same story?')"
    ),
    md(
        "## Tool 1 - Eli5, **global**: and a built-in trap\n"
        "\n"
        "Eli5 gives you two global importances, and they are **not the same thing**:\n"
        "\n"
        "- `explain_weights` on a tree model returns the forest's **internal Gini importance** - computed\n"
        "  from the training splits. It is free, and it is **biased toward high-cardinality features**\n"
        "  (a continuous feature gets more chances to look useful).\n"
        "- `PermutationImportance` **shuffles a feature on held-out data** and measures the damage. It is\n"
        "  model-agnostic, honest about generalisation, and slower.\n"
        "\n"
        "Most people print the first one and call it importance. Watch what happens when you print both."
    ),
    code(
        "import eli5\n"
        "from eli5.sklearn import PermutationImportance\n"
        "\n"
        "gini = pd.Series(model.feature_importances_, index=FEATS)\n"
        "\n"
        "perm = PermutationImportance(model, random_state=SEED, n_iter=10).fit(X_te, y_te)\n"
        "permimp = pd.Series(perm.feature_importances_, index=FEATS)\n"
        "\n"
        "cmp = pd.DataFrame({'gini (train, built-in)': gini,\n"
        "                    'permutation (test, honest)': permimp})\n"
        "cmp['gini rank'] = cmp['gini (train, built-in)'].rank(ascending=False).astype(int)\n"
        "cmp['perm rank'] = cmp['permutation (test, honest)'].rank(ascending=False).astype(int)\n"
        "cmp['rank shift'] = cmp['gini rank'] - cmp['perm rank']\n"
        "\n"
        "print(cmp.sort_values('perm rank').round(4).to_string())\n"
        "\n"
        "rho = spearmanr(cmp['gini rank'], cmp['perm rank']).statistic\n"
        "print(f'\\nSpearman rank correlation between the two \"importances\": {rho:.3f}')\n"
        "print('Both are labelled \"feature importance\". They do not agree. Report the one you can defend.')"
    ),
    md(
        "## Tool 1b - Eli5, **local**: and a landmine\n"
        "\n"
        "Same library, different scope. For a tree ensemble Eli5 walks the actual decision path and reports\n"
        "each feature's contribution - a *faithful* decomposition, not an approximation.\n"
        "\n"
        "Faithful **to which class**, though? Watch carefully."
    ),
    code(
        "i = 7\n"
        "wine = X_te.iloc[[i]]\n"
        "p = model.predict_proba(wine)[0, 1]\n"
        "print(f'Wine #{X_te.index[i]} -> P(good) = {p:.3f} '\n"
        "      f'(actual: {\"good\" if y_te.iloc[i] else \"not good\"})\\n')\n"
        "\n"
        "def eli5_weights(target):\n"
        "    e = eli5.explain_prediction(model, wine.iloc[0], feature_names=FEATS,\n"
        "                                targets=target, top=len(FEATS)).targets[0]\n"
        "    fw = e.feature_weights\n"
        "    w = {x.feature: x.weight for x in list(fw.pos) + list(fw.neg)}\n"
        "    return e.target, w.get('volatile_acidity')\n"
        "\n"
        "print('Ask Eli5 to explain each class and watch the weight for volatile_acidity:')\n"
        "for t in (None, [0], [1]):\n"
        "    cls, va = eli5_weights(t)\n"
        "    print(f'  targets={str(t):5s} -> Eli5 says it explained class {cls}, '\n"
        "          f'volatile_acidity = {va:+.4f}')\n"
        "\n"
        "print('\\nThe class LABEL changes. The WEIGHTS do not. Eli5 hands you the class-0')\n"
        "print('decomposition and stamps it with whichever class you asked for.')\n"
        "print('Read as \"contribution to P(good)\", every sign is inverted. Keep reading.')"
    ),
    md(
        "### Which sign is actually right?\n"
        "\n"
        "SHAP and Eli5 now contradict each other on `volatile_acidity` - one says it pushed this wine\n"
        "**toward** good, the other **away**. They cannot both be right, and no chart will tell you which is.\n"
        "\n"
        "So stop reading explanations and **interrogate the model directly**. Volatile acidity is the vinegar\n"
        "taint in wine - domain knowledge says more of it is worse. Does the model agree?"
    ),
    code(
        "print(f\"this wine's volatile_acidity = {wine['volatile_acidity'].values[0]:.2f} \"\n"
        "      f\"(dataset mean {X['volatile_acidity'].mean():.3f})\\n\")\n"
        "\n"
        "print('Ground truth in the data - share of GOOD wines by volatile-acidity quartile:')\n"
        "print(df.groupby(pd.qcut(df['volatile_acidity'], 4), observed=True)['good']\n"
        "        .mean().round(3).to_string())\n"
        "\n"
        "print('\\nIntervention - sweep THIS wine\\'s volatile_acidity, watch the model:')\n"
        "for v in [0.2, 0.4, 0.56, 0.8, 1.0]:\n"
        "    c = wine.copy(); c['volatile_acidity'] = v\n"
        "    print(f'  volatile_acidity={v:.2f} -> P(good)={model.predict_proba(c)[0,1]:.3f}')\n"
        "\n"
        "print('\\nUnambiguous: high volatile acidity HURTS. Drop this wine to 0.20 and P(good)')\n"
        "print('goes 0.040 -> 0.407. Its 0.56 is holding it DOWN.\\n')\n"
        "print('  SHAP said  -0.0744  -> pushed AWAY from good.  CORRECT.')\n"
        "print('  Eli5 said  +0.0764  -> pushed TOWARD good.     WRONG SIGN.')\n"
        "print('\\nEli5 would tell you the vinegar taint is what made the wine good.')\n"
        "print('It is confident, it is well formatted, and it is backwards.')"
    ),
    md(
        "## Tool 2 - LIME: a **local surrogate**\n"
        "\n"
        "LIME takes a completely different route. It does not open the model at all. It:\n"
        "\n"
        "1. **jitters** the instance to make thousands of fake neighbours,\n"
        "2. asks the black box to label them,\n"
        "3. fits a **simple linear model** to that local cloud,\n"
        "4. hands you *that* model's coefficients as the explanation.\n"
        "\n"
        "So a LIME explanation is a **model of a model**. Which raises the obvious question, and nobody who\n"
        "ships a LIME chart ever seems to ask it: *is the surrogate any good?* It reports an R² - check it."
    ),
    code(
        "from lime.lime_tabular import LimeTabularExplainer\n"
        "\n"
        "lime_exp = LimeTabularExplainer(\n"
        "    X_tr.values, feature_names=FEATS, class_names=['not good', 'good'],\n"
        "    mode='classification', random_state=SEED, discretize_continuous=True)\n"
        "\n"
        "e = lime_exp.explain_instance(wine.values[0], model.predict_proba, num_features=6)\n"
        "print(f'LIME local surrogate R2 = {e.score:.3f}   '\n"
        "      f'(local prediction {e.local_pred[0]:.3f} vs true model {p:.3f})\\n')\n"
        "print('LIME explanation (rule -> weight):')\n"
        "for rule, w in e.as_list():\n"
        "    print(f'  {w:+.4f}  {rule}')\n"
        "print('\\nNote LIME explains RULES (\"alcohol > 11.10\"), not raw features. That readability')\n"
        "print('is its selling point - and it is why it cannot be compared to SHAP naively.')"
    ),
    md(
        "## Two checks on LIME that nobody runs\n"
        "\n"
        "**Check 1 - stability.** LIME's neighbours are randomly sampled. Same instance, same model,\n"
        "different seed: same explanation?\n"
        "\n"
        "**Check 2 - is the surrogate even fitting?** LIME reports `score` (the local R²) and `local_pred`\n"
        "(what the *surrogate* predicts). If `local_pred` is nowhere near the black box's actual output, the\n"
        "surrogate is not approximating the model at that point - and its coefficients are explaining a\n"
        "**model that does not exist**.\n"
        "\n"
        "Nobody checks #2. It turns out to be the one that bites."
    ),
    code(
        "runs = []\n"
        "for seed in range(5):\n"
        "    ex = LimeTabularExplainer(X_tr.values, feature_names=FEATS,\n"
        "                              class_names=['not good', 'good'], mode='classification',\n"
        "                              random_state=seed, discretize_continuous=True)\n"
        "    r = ex.explain_instance(wine.values[0], model.predict_proba, num_features=5)\n"
        "    top = [FEATS[f] for f, _ in r.as_map()[1]]\n"
        "    runs.append(top)\n"
        "    print(f'seed {seed}: R2={r.score:.3f}  local_pred={r.local_pred[0]:.3f}  top-5 = {top}')\n"
        "\n"
        "same_order = all(r == runs[0] for r in runs)\n"
        "same_set = all(set(r) == set(runs[0]) for r in runs)\n"
        "print(f'\\nCheck 1 - identical top-5 SET across seeds?   {same_set}')\n"
        "print(f'Check 1 - identical top-5 ORDER across seeds? {same_order}')\n"
        "print('  -> Be fair to LIME: the headline feature is stable here. Only the tail reorders.')\n"
        "print('     Real, but survivable. Now the one that is not.\\n')\n"
        "\n"
        "print(f'Check 2 - the black box says P(good) = {p:.3f}')\n"
        "print(f\"          LIME's surrogate says     = {e.local_pred[0]:.3f}\")\n"
        "print(f'          local R2                  = {e.score:.3f}')\n"
        "print(f'          absolute error            = {abs(e.local_pred[0] - p):.3f}'\n"
        "      f'  <-- that is {abs(e.local_pred[0] - p) / max(p, 1e-9):.0f}x the true value')\n"
        "print('\\nThe surrogate does not reproduce the prediction it claims to explain.')\n"
        "print('Its coefficients are a faithful account of a model that was never deployed.')"
    ),
    md(
        "## The showdown: do the explainers **agree**?\n"
        "\n"
        "Same wine, same model, three explainers. We rank the features by each method's local attribution\n"
        "and compare. SHAP and Eli5 both decompose the *actual* tree paths, so they ought to line up. LIME\n"
        "fits a surrogate, so it is free to disagree - and it is the one people show to customers."
    ),
    code(
        "import shap\n"
        "\n"
        "sv = shap.TreeExplainer(model)(X_te)\n"
        "sv = sv[..., 1] if sv.values.ndim == 3 else sv\n"
        "shap_local = pd.Series(sv.values[i], index=FEATS)\n"
        "\n"
        "fw = eli5.explain_prediction(model, wine.iloc[0], feature_names=FEATS,\n"
        "                             targets=[1], top=len(FEATS)).targets[0].feature_weights\n"
        "eli5_raw = pd.Series(0.0, index=FEATS)\n"
        "for w in list(fw.pos) + list(fw.neg):\n"
        "    if w.feature in eli5_raw.index:\n"
        "        eli5_raw[w.feature] = w.weight\n"
        "eli5_fixed = -eli5_raw          # negate: it gave us the class-0 decomposition\n"
        "\n"
        "lime_local = pd.Series(0.0, index=FEATS)\n"
        "for fidx, w in e.as_map()[1]:\n"
        "    lime_local[FEATS[fidx]] = w\n"
        "\n"
        "board = pd.DataFrame({'SHAP': shap_local,\n"
        "                      'Eli5 (raw)': eli5_raw,\n"
        "                      'Eli5 (negated)': eli5_fixed,\n"
        "                      'LIME': lime_local})\n"
        "ranks = board.abs().rank(ascending=False)\n"
        "board['SHAP rank'] = ranks['SHAP'].astype(int)\n"
        "board['LIME rank'] = ranks['LIME'].astype(int)\n"
        "print('Local attributions for ONE wine, by three explainers:\\n')\n"
        "print(board.round(4).sort_values('SHAP rank').to_string())\n"
        "\n"
        "print('\\n--- do they agree on the RANKING? (Spearman on |attribution|) ---')\n"
        "for a, b in [('SHAP', 'Eli5 (raw)'), ('SHAP', 'LIME'), ('Eli5 (raw)', 'LIME')]:\n"
        "    print(f'  {a:11s} vs {b:11s}: {spearmanr(ranks[a], ranks[b]).statistic:+.3f}')\n"
        "\n"
        "print('\\n--- do they agree on the DIRECTION? (sign agreement with SHAP) ---')\n"
        "for name, s in [('Eli5 (raw)', eli5_raw), ('Eli5 (negated)', eli5_fixed), ('LIME', lime_local)]:\n"
        "    nz = (shap_local != 0) & (s != 0)\n"
        "    agree = (np.sign(shap_local[nz]) == np.sign(s[nz])).mean()\n"
        "    print(f'  {name:15s}: {agree:.0%} of features point the same way as SHAP')\n"
        "\n"
        "print('\\nRanking agreement hid the problem completely: Eli5 (raw) tracks SHAP at +0.98,')\n"
        "print('yet points the OPPOSITE WAY on every feature. Rank correlation is not enough.')\n"
        "print('Negate it and it becomes the best explanation on the board. Nothing told you to.')"
    ),
    md(
        "## Tool 3 - Mlxtend: the only one that shows you the **boundary**\n"
        "\n"
        "Eli5, LIME and SHAP all answer *\"how much did each feature contribute?\"* - they are **attribution**\n"
        "methods. Mlxtend answers a different question entirely: *\"what shape did the model actually carve\n"
        "out of the feature space?\"*\n"
        "\n"
        "You can only draw it in 2D, which is the catch. But it makes something visible that no bar chart\n"
        "can: **where the model is confident, where it is guessing, and how jagged (overfit) it is.**"
    ),
    code(
        "from mlxtend.plotting import plot_decision_regions\n"
        "from sklearn.tree import DecisionTreeClassifier\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.preprocessing import StandardScaler\n"
        "from sklearn.pipeline import make_pipeline\n"
        "\n"
        "pair = ['alcohol', 'volatile_acidity']   # the two features that mattered most\n"
        "X2_tr = X_tr[pair].values.astype(float)\n"
        "X2_te = X_te[pair].values.astype(float)\n"
        "\n"
        "zoo = {\n"
        "    'LogReg (linear)': make_pipeline(StandardScaler(), LogisticRegression(random_state=SEED)),\n"
        "    'Tree depth=3 (blocky)': DecisionTreeClassifier(max_depth=3, random_state=SEED),\n"
        "    'RandomForest (jagged)': RandomForestClassifier(n_estimators=300, random_state=SEED),\n"
        "}\n"
        "\n"
        "fig, axes = plt.subplots(1, 3, figsize=(16, 4.6))\n"
        "for ax, (name, clf) in zip(axes, zoo.items()):\n"
        "    clf.fit(X2_tr, y_tr.values)\n"
        "    plot_decision_regions(X2_te, y_te.values, clf=clf, legend=0, ax=ax,\n"
        "                          colors='#3498db,#e74c3c')\n"
        "    ax.set_xlabel(pair[0]); ax.set_ylabel(pair[1])\n"
        "    ax.set_title(f'{name}\\ntest acc (2 features) = '\n"
        "                 f'{accuracy_score(y_te, clf.predict(X2_te)):.3f}', fontsize=10)\n"
        "fig.suptitle('Mlxtend - the decision boundary each model carved (blue = not good, red = good)',\n"
        "             fontsize=12)\n"
        "fig.tight_layout()\n"
        "fig.savefig(OUT / 'a4_decision_regions.png', dpi=130, bbox_inches='tight')\n"
        "plt.show()\n"
        "print('Left: a straight line - underfits, but you could defend it in a meeting.')\n"
        "print('Middle: axis-aligned blocks - literally the if/else rules, drawn.')\n"
        "print('Right: a jagged coastline - higher accuracy, and islands that are pure memorisation.')"
    ),
    md(
        "## Discussion (the brief's question)\n"
        "\n"
        "**\"How does having access to these tools compare with the explainer dashboard?\"**\n"
        "\n"
        "The dashboard is a *packaging* decision, not a *capability* one - it is a UI over exactly these\n"
        "calls. The real difference is that using the libraries directly forces you to see the thing the\n"
        "dashboard smooths over: **the explainers disagree, and none of them announces it.**\n"
        "\n"
        "| Tool | Question it answers | Scope | Faithful to the model? | Watch out |\n"
        "|---|---|---|---|---|\n"
        "| **Eli5** `explain_weights` | which features did the forest split on? | global | yes (but *training* Gini) | biased to high-cardinality features |\n"
        "| **Eli5** `PermutationImportance` | what breaks if I shuffle this? | global | yes (held-out) | slow; correlated features share credit |\n"
        "| **Eli5** `explain_prediction` | what drove *this* one? | local | magnitudes yes, **signs inverted** | returns class-0 weights whatever `targets` says - **negate them** |\n"
        "| **LIME** | what drove this one, *in plain rules*? | local | **no - it is a surrogate** | **check `score` (R²) and `local_pred`** - here the surrogate missed the prediction by 8x |\n"
        "| **SHAP** | what drove this one, *additively*? | local + global | yes, with a guarantee | slow on big data |\n"
        "| **Mlxtend** | what **shape** is the boundary? | global | yes | 2D only |\n"
        "\n"
        "### The four things this notebook actually proved\n"
        "\n"
        "1. **Eli5 gave us a confident, backwards explanation - and we caught it.** For a binary classifier,\n"
        "   `explain_prediction` returns the **class-0** decision-path weights and stamps them with whatever\n"
        "   class you asked for. `targets=None`, `targets=[0]`, `targets=[1]` all return **the identical\n"
        "   weights**; only the printed label changes. Read as *\"contribution to P(good)\"* - which is exactly\n"
        "   how anyone would read it - **every sign is inverted**. Eli5 reports `volatile_acidity = +0.076`\n"
        "   (helped this wine be good). The vinegar taint. We verified against the model by intervention:\n"
        "   drop this wine's volatile acidity 0.56 -> 0.20 and P(good) goes **0.040 -> 0.407**. It was\n"
        "   *hurting*. **SHAP had the sign right (-0.074); Eli5 had it backwards.**\n"
        "2. **Rank correlation would never have caught it.** Eli5 (raw) tracks SHAP at **+0.98** on ranking -\n"
        "   a number that looks like agreement and would sail through any review - while pointing the\n"
        "   **opposite way on every single feature**. Agreement on *importance* is not agreement on\n"
        "   *direction*, and only one of those is what you tell a customer.\n"
        "3. **LIME disagreed too, and its own output said so.** LIME ranks `alcohol` **1st** (+0.168); SHAP\n"
        "   ranks it **8th of 11** (+0.006). Why: LIME's surrogate predicts **0.335** for a wine the model\n"
        "   scores at **0.040** - off by ~7x, local R² **0.51**. It never fit the neighbourhood, so its\n"
        "   coefficients faithfully describe **a model that was never deployed**. That failure was legible\n"
        "   the whole time, in a number LIME prints and nobody reads.\n"
        "4. **Attribution is not the whole story.** Mlxtend shows the RandomForest's boundary is a jagged\n"
        "   coastline with isolated islands - visibly memorised. No bar chart from any other tool contains\n"
        "   that information.\n"
        "\n"
        "> **In fairness to LIME:** its top feature was *stable* across 5 seeds. The instability is real but\n"
        "> confined to the tail, and it is not the damning result. The unfitted surrogate is.\n"
        "\n"
        "> **In fairness to Eli5:** its *magnitudes* are excellent - negate them and it is the best explainer\n"
        "> on the board. The library is not broken. It is **silently ambiguous**, which is worse, because a\n"
        "> broken tool announces itself.\n"
        "\n"
        "### So what\n"
        "\n"
        "This is the module's warning arriving with receipts. Aha (Res. 4) says *a wrong explanation is worse\n"
        "than no explanation*, because it manufactures **unearned trust**. We did not have to construct a\n"
        "contrived example to show it. We pointed four standard tools at one model and one wine, and got\n"
        "materially different stories - each rendered with total confidence, none carrying a warning label.\n"
        "\n"
        "The defence is not a better library - it is a **habit**. Every claim in this notebook that turned out\n"
        "to be wrong was caught the same way: by **going back to the model and intervening on it**. Change the\n"
        "feature, re-predict, see which way it moves. That takes three lines and it is the only thing here\n"
        "that cannot lie to you, because it is not an explanation - it is the model itself.\n"
        "\n"
        "Then **triangulate** (run two explainers; if they diverge, say so out loud) and **govern** (Sowden,\n"
        "Res. 5 - someone must be accountable for which explanation ships).\n"
        "\n"
        "**Carry into Assessment 2:** if you put SHAP in the discussion section, (a) sanity-check the **sign**\n"
        "of your top feature with a quick intervention sweep, and (b) run permutation importance alongside it.\n"
        "*\"Two independent explainers agree on the top three features, and an intervention confirms the\n"
        "direction\"* is a defensible claim. One bar chart from one library is a liability - as this notebook\n"
        "just demonstrated on itself."
    ),
]


if __name__ == '__main__':
    build('activity1_what_if_wine.ipynb', a1)
    build('activity2_bank_loan_explainability.ipynb', a2)
    build('activity3_shap_titanic.ipynb', a3)
    build('activity4_eli5_lime_mlxtend.ipynb', a4)
