[server]
fileWatcherType = "none"
folderWatchBlacklist = [
  "venv",
  ".venv",
  "env",
  ".env",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "/Users/luisfaria/Desktop/sEngineer/masters_SWEAI/T1-Software-Engineering-Principles/projects/clinictrends_ai/venv/lib/python3.10/site-packages"
]