name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout only TTrack_v1 folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            T1-Software-Development-Management/projects/TTrack_v1
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd T1-Software-Development-Management/projects/TTrack_v1
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          cd T1-Software-Development-Management/projects/TTrack_v1
          pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTrack-exe
          path: T1-Software-Development-Management/projects/TTrack_v1/dist/*.exe
